# Use root/example as user/password credentials
version: '3.1'

services:

  gomongo:
    image: mongo:latest
    container_name: gomongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  gomongo-express:
    image: mongo-express
    container_name: gomongo-express
    restart: always
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@gomongo:27017/
    depends_on:
        - gomongo

